### PR TITLE
add files from blocktalk to scaffold

### PR DESCRIPTION
**Pull request by MrDSGC**
- pulled in blocktalk submodule
- removed twitter api code
- refactored login CTA

### CODE REVIEW

**Review by bthaile — APPROVED** [review]
PR lgtm

**Comment by chasefleming** [comment]
Couple notes:

- the login probably can just be a “login with wallet” button now and not a dropdown since there’s no twitter login anymore
- would either stick to “mint” or “post” as the language and remove the other. maybe post over mint since not taking tweets anymore
- remove twitter env vars from the example env file
- uninstall next-auth package and twitter-api-sdk package
- maybe take out twitter share link although might be cool to keep

**Review by chasefleming — CHANGES_REQUESTED** [review]
left a note

**Review by chasefleming — APPROVED** [review]

**Review by fotescodev — APPROVED** [review]
Great!

**Pull request merged**
